; PlatformIO Projektkonfiguration
; Repo-Struktur bleibt erhalten: Sources liegen in /firmware

[platformio]
src_dir = firmware

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

